---

- name: Gather existing Google Chrome executable path
  command: 'which google-chrome'
  register: google_chrome_installed
  changed_when: google_chrome_installed.rc != 0
  failed_when: no
  become: True
  become_user: '{{ params.user.username }}'

- name: Set fact google_chrome_not_installed
  set_fact:
    google_chrome_not_installed={{ google_chrome_installed.changed }}

- name: Add Google linux signing key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  become: True
  when: google_chrome_not_installed

- name: Add Google Chrome repo
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    state: present
    update_cache: yes
  become: True
  when: google_chrome_not_installed

- name: Install Google Chrome
  apt:
    name: "google-chrome-stable"
    state: present
  become: True
  when: google_chrome_not_installed

- name: Set fact necessary_menu_items
  set_fact:
    necessary_menu_items: "{{ necessary_menu_items }} + [ 'google-chrome.dockitem' ]"
