---

- name: Set fact pycharm_version
  set_fact:
    pycharm_version='2017.3.2'

- name: Install PyCharm
  include_role:
    name: tersmitten.pycharm
  vars:
    pycharm_edition: community
  become: True

- name: Add desktop entry
  template:
    src: '{{ item }}.j2'
    dest: '/usr/share/applications/{{ item }}'
    force: no
    mode: 0644
  with_items:
    - jetbrains-pycharm-ce.desktop
  become: True

- name: Set fact necessary_menu_items
  set_fact:
    necessary_menu_items: "{{ necessary_menu_items }} + [ 'jetbrains-pycharm-ce.dockitem' ]"
