---

- name: Create download dir
  file:
    path: "{{ pycharm_downloads_path }}"
    state: directory
  become: True

- name: Download
  get_url:
    url: "http://download.jetbrains.com/python/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
  become: True

- name: Install
  unarchive:
    src: "{{ pycharm_downloads_path }}/pycharm-{{ pycharm_edition }}-{{ pycharm_version }}.tar.gz"
    dest: "{{ pycharm_install_prefix }}"
    creates: "{{ pycharm_install_prefix }}/pycharm-{{ pycharm_version }}"
    copy: false
  become: True

- name: Add desktop entry
  template:
    src: '{{ item }}.j2'
    dest: '/usr/share/applications/{{ item }}'
    force: no
    mode: 0644
  with_items:
    - jetbrains-pycharm-ce.desktop
  become: True

- name: Set fact necessary_menu_items
  set_fact:
    necessary_menu_items: "{{ necessary_menu_items }} + [ 'jetbrains-pycharm-ce.dockitem' ]"
