- name: Installing AnsibleGalaxy roles based on requirements file
  local_action: command ansible-galaxy install -r requirements.yml --roles-path ./roles
  register: ansible_galaxy_install_command
  changed_when: ansible_galaxy_install_command.stdout is search("was installed successfully")

- name: Installing additional roles
  local_action: "command ansible-galaxy install --roles-path ./roles/additional git+{{ item }},master"
  with_items: "{{ params.roles }}"
  register: ansible_galaxy_install_command
  changed_when: ansible_galaxy_install_command.stdout is search("was installed successfully")
  no_log: True
