---
- name: Retrieve 'developers' group data
  command: getent group developers
  register: getent_group
  changed_when: False
  failed_when: False

- name: Create 'developers' group
  group: name=developers state=present
  when: getent_group.rc != 0
  become: True

- name: Retrieve user data
  command: getent passwd {{ params.user.username }}
  register: getent_passwd
  changed_when: False
  failed_when: False

- name: Create development user
  user: name={{ params.user.username }} password={{ params.user.password | password_hash('sha512') }} shell=/bin/bash
  when: getent_passwd.rc != 0
  become: True

- name: Set groups for the development user
  user: name={{ params.user.username }} groups=developers,sudo
  become: True

- name: Set development user name
  command: chfn -f '{{ params.user.fullname }}' {{ params.user.username }}
  when: getent_passwd.rc != 0 or params.user.fullname not in getent_passwd.stdout
  become: True

- name: Disable GUI login as user 'vagrant' and 'ubuntu'
  blockinfile:
    dest: /var/lib/AccountsService/users/{{ item }}
    block: |
      [User]
      SystemAccount=true
    marker: ""
    create: yes
  with_items:
    - vagrant
    - ubuntu
  changed_when: False
  become: True

- name: Disable GUI login as guest
  blockinfile:
    dest: /etc/lightdm/lightdm.conf.d/50-no-guest.conf
    block: |
      [Seat:*]
      allow-guest=false
    marker: ""
    create: yes
  changed_when: False
  become: True

- name: Set fact plank_dock_configuration_dir
  set_fact:
    plank_dock_configuration_dir='/home/{{ params.user.username }}/.config/plank/dock1/launchers'

- name: Ensures plank dock configuration dir exists
  file: path={{ plank_dock_configuration_dir }} state=directory
  become: True
  become_user: '{{ params.user.username }}'

- name: Remove unecessary dock items
  file: path='{{ plank_dock_configuration_dir }}/{{ item }}' state=absent
  with_items:
    - org.pantheon.photos.dockitem
    - org.pantheon.switchboard.dockitem
  become: True
  become_user: '{{ params.user.username }}'

- name: Add necessary dock items
  template:
    src: '{{ item }}'
    dest: '{{ plank_dock_configuration_dir }}/{{ item }}'
    force: no
    mode: 0644
  with_items:
    - org.pantheon.terminal.dockitem
  become: True
  become_user: '{{ params.user.username }}'
