---

- name: Running extra (private) roles
  include_role:
    name: "roles/private/{{ item.rsplit('/', 1)[1].split('.')[0] }}"
    private: True
  with_items: "{{ params.roles }}"
  vars:
    default_user: "{{ params.user.username }}"
    default_user_password: "{{ params.user.password }}"

- name: Clean-up extra (private) roles
  file:
    state: "{{ item }}"
    path: "roles/private"
  with_items:
    - absent
    - directory
