---

- name: Set fact workspace_dir
  set_fact:
    workspace_dir="/home/{{ params.user.username }}/workspace"

- name: Create workspace directory
  file:
    state: directory
    path: "{{ workspace_dir }}"
  become: True
  become_user: "{{ params.user.username }}"

- name: Checkout or update workspace projects
  git:
    repo: "{{ item }}"
    dest: "{{ workspace_dir }}/{{ item.rsplit('/', 1)[1].rsplit('.git')[0] }}"
  become: True
  become_user: "{{ params.user.username }}"
  with_items: "{{ params.workspace.gitrepos }}"
  no_log: True
