---
- name: Set fact whiskermenu_configuration_dir
  set_fact:
    whiskermenu_configuration_dir='/home/{{ params.user.username }}/.config/xfce4/panel'

- name: Ensures whiskermenu configuration dir exists
  file: path={{ whiskermenu_configuration_dir }} state=directory
  become: True
  become_user: '{{ params.user.username }}'

- name: Init whiskermenu configuration file
  template:
    src: whiskermenu-1.rc.j2
    dest: '{{ whiskermenu_configuration_dir }}/whiskermenu-1.rc'
    force: no
    mode: 0644
  become: True
  become_user: '{{ params.user.username }}'
