---

- name: Install aptitude
  apt: name=aptitude state=latest install_recommends=no
  become: True

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: True

- name: Install desktop environment prerequisites
  apt: name={{ item }} state=latest install_recommends=no
  with_items:
    - software-properties-common
    - xorg
    - xinit
    - lightdm
  become: True

- name: Add desktop environment repositories
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'ppa:elementary-os/stable'
    - 'ppa:elementary-os/os-patches'
  become: True

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
  become: True

- name: Install Elementary desktop environment
  apt: name={{ item }} state=latest
  with_items:
    - elementary-theme
    - elementary-icon-theme
    - elementary-default-settings
    - elementary-desktop
  become: True

- name: Remove unecessary applications
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - pantheon-mail
    - audience
    - noise
    - byobu
    - epiphany-browser
    - epiphany
    - appcenter
  become: True

- name: Clean apt cache
  command: "apt clean"
  become: True

- name: Autoremove old packages
  command: "apt autoremove --purge -y"
  become: True
