- name: Installing AnsibleGalaxy roles based on requirements file
  local_action: command ansible-galaxy install -r requirements.yml --roles-path ./roles

- name: Installing extra (private) roles
  local_action: command ansible-galaxy install --roles-path ./roles/private {{ item }}
  with_items: "{{ params.roles }}"
