- name: Installing AnsibleGalaxy roles based on requirements file
  local_action: command ansible-galaxy install -r requirements.yml --roles-path ./roles

- name: Installing additional roles
  local_action: "command ansible-galaxy install --force --roles-path ./roles/additional git+{{ item }},master"
  with_items: "{{ params.roles }}"
  no_log: True
