---
- name: Check current locale configuration
  command: "localectl status"
  register: localectl_status
  changed_when: False

- name: Set configured locale for the keyboard
  command: "localectl set-keymap {{ params.vm.keyboard_locale }}"
  become: True
  when: "'VC Keymap: {{ params.vm.keyboard_locale }}' not in localectl_status.stdout"

- name: Set timezone
  timezone:
    name: "{{ params.vm.timezone }}"
  become: True
