---

- name: Add Sublime Apt signing key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: True

- name: Install apt-transport-https
  apt: name=apt-transport-https state=latest
  become: True

- name: Select stable channel
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
  become: True

- name: Install Sublime Text
  apt: name=sublime-text state=latest update_cache=yes
  become: True  

- name: Set fact necessary_menu_items
  set_fact:
    necessary_menu_items: "{{ necessary_menu_items }} + [ 'sublime_text.dockitem' ]"
