---

- name: Install Intellij
  include_role:
    name: gantsign.intellij
  vars:
    intellij_default_jdk_home: /usr/lib/jvm/java-8-oracle
    intellij_default_maven_home: /usr/share/maven

- name: Add necessary dock items
  template:
    src: '{{ item }}'
    dest: '{{ plank_dock_configuration_dir }}/{{ item }}'
    force: no
    mode: 0644
  with_items:
    - jetbrains-idea-ce.dockitem
  become: True
  become_user: '{{ params.user.username }}'
