---

- name: Provisioning

  hosts: all

  tasks:

    - import_tasks: tasks/install-roles.yml
    - import_tasks: tasks/setup-locale.yml
    - import_tasks: tasks/install-desktop-environment.yml
    - import_tasks: tasks/create-user.yml

    - name: Install Google Chrome
      include_role:
        name: fagia.chrome
      when: params.apps.install.chrome

    - name: Install MariaDB
      include_role:
        name: fagia.mariadb
      when: params.apps.install.mariadb

    - name: Install Java
      include_role:
        name: fagia.java
      when: params.apps.install.java

    - name: Install Maven
      include_role:
        name: fagia.maven
      when: params.apps.install.maven

    - name: Install Gradle
      include_role:
        name: fagia.gradle
      when: params.apps.install.gradle

    - name: Install IntelliJ Idea
      include_role:
        name: fagia.intellij
      when: params.apps.install.java and params.apps.install.maven and params.apps.install.intellij_idea