---

- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest
  become: True

- name: Add MariaDB apt key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: '0xF1656F24C74CD1D8'
    state: present
  become: True

- name: Add MariaDB Repository
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://ftp.heanet.ie/mirrors/mariadb/repo/10.2/ubuntu xenial main'
  become: True

- name: Install MariaDB
  apt: name=mariadb-server state=latest update_cache=yes
  become: True

- name: Install python module
  apt: name=python-mysqldb state=present
  become: True

- name: Set fact secure_mariadb_sql
  set_fact:
    secure_mariadb_sql='secure_mariadb.sql'

- name: Set fact secure_mariadb_sql_path
  set_fact:
    secure_mariadb_sql_path='/home/{{ params.user.username }}/{{ secure_mariadb_sql }}'

- name: Add secure MariaDB sql script
  template:
    src: 'secure_mariadb.sql.j2'
    dest: '{{ secure_mariadb_sql_path }}'
    mode: 0644
  become: True
  become_user: '{{ params.user.username }}'

- name: Execute secure MariaDB sql script
  shell: 'mysql -sfu root < {{ secure_mariadb_sql_path | quote }}'
  ignore_errors: True
  become: True
  become_user: '{{ params.user.username }}'

- name: Remove secure MariaDB sql script
  file:
    path: '{{ secure_mariadb_sql_path }}'
    state: absent
  become: True
  become_user: '{{ params.user.username }}'
