---

- when: params.apps.install.docker
  become: True
  block:
    - name: Install pip
      apt: name=python-pip state=latest
    - name: Install python support for Docker
      pip:
        name: docker
        state: latest
    - name: Install Docker
      include_role:
        name: geerlingguy.docker
      vars:
        ansible_become: yes
    - name: Ensure group docker exists
      group:
        name: docker
        state: present
    - name: "Appending the group docker to {{ params.user.username }}'s groups"
      user:
        name: "{{ params.user.username }}"
        groups: docker
        append: yes
