---

- name: Install Java
  when: params.apps.install.java or params.apps.install.intellij_idea or params.apps.install.pycharm
  become: True
  block:
    - name: Install add-apt-repostory
      apt: name=software-properties-common state=latest
    - name: Add Oracle Java Repository
      apt_repository:
        repo: "deb http://ppa.launchpad.net/webupd8team/java/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    - name: Accept Java 8 License
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    - name: Install Oracle Java 8
      apt:
        state: latest
        allow_unauthenticated: yes
        name:
          - oracle-java8-installer
          - ca-certificates
          - oracle-java8-set-default
