---

- name: Install MailHog
  when: params.apps.install.mailhog
  block:
  - name: Set MailHog facts
    set_fact:
      mailhog_dir: /opt/mailhog
      mailhog_png_file: /opt/mailhog/mailhog.png
  - include_role:
      name: geerlingguy.mailhog
    vars:
      mailhog_install_dir: "{{ mailhog_dir }}"
      ansible_become: yes
  - name: Add MailHog launcher
    when: params.apps.install.chrome
    block:
    - name: Add MailHog icon
      copy:
        src: files/icons/mailhog.png
        dest: "{{ mailhog_png_file }}"
      become: True
    - name: Add MailHog desktop entry
      template:
        src: mailhog.desktop.j2
        dest: /usr/share/applications/mailhog.desktop
        force: no
        mode: 0644
      become: True
    - name: Set fact necessary_menu_items
      set_fact:
        necessary_menu_items: "{{ necessary_menu_items }} + [ 'mailhog' ]"
  - name: Configure MailHog for PHP
    when: params.apps.install.php
    block:
    - name: Retrieve php.ini file paths
      find:
        paths: /etc/php
        patterns: php.ini
        recurse: True
      register: found_php_ini
    - name: Configure mhsendmail for PHP
      lineinfile:
        path: "{{ item.path }}"
        regexp: ".*sendmail_path *=.*"
        line: 'sendmail_path = "{{ mailhog_dir }}/mhsendmail"'
      with_items: "{{ found_php_ini.files }}"
      become: True
