---

- name: Install PHP
  when: params.apps.php.install
  become: True
  block:
    - name: Add repository for older PHP versions
      apt_repository:
        repo: "deb http://ppa.launchpad.net/ondrej/php/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
      when: params.apps.php.version != ""
    - name: Install PHP packages
      apt:
        state: latest
        allow_unauthenticated: yes
        name:
          - "php{{ params.apps.php.version }}"
          - "php{{ params.apps.php.version }}-mcrypt"
          - "php{{ params.apps.php.version }}-gd"
          - "php{{ params.apps.php.version }}-xml"
