---

- name: Install PyCharm
  when: params.apps.install.pycharm
  block:
    - include_role:
        name: fagia.pycharm
    - name: Set fact necessary_menu_items
      set_fact:
        necessary_menu_items: "{{ necessary_menu_items }} + [ 'jetbrains-pycharm-ce' ]"
